"""change in review table

Revision ID: eec84658fab3
Revises: 71cee69f2bed
Create Date: 2024-07-02 16:46:35.922388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eec84658fab3'
down_revision: Union[str, None] = '71cee69f2bed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('carts', 'price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=2),
               existing_nullable=False)
    op.alter_column('carts', 'total_price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=2),
               existing_nullable=False)
    op.alter_column('order', 'total_price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=2),
               existing_nullable=False)
    op.alter_column('payments', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=3),
               existing_nullable=False)
    op.alter_column('products', 'product_price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=2),
               existing_nullable=False)
    op.alter_column('products', 'discount_percent',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5, asdecimal=2),
               existing_nullable=False)
    op.alter_column('products', 'discount_price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=2),
               existing_nullable=False)
    op.add_column('reviews', sa.Column('comment', sa.String(length=200), nullable=False))
    op.add_column('reviews', sa.Column('rating', sa.Integer(), nullable=False))
    op.drop_column('reviews', 'stars')
    op.drop_column('reviews', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('reviews', sa.Column('stars', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('reviews', 'rating')
    op.drop_column('reviews', 'comment')
    op.alter_column('products', 'discount_price',
               existing_type=sa.Float(precision=10, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('products', 'discount_percent',
               existing_type=sa.Float(precision=5, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('products', 'product_price',
               existing_type=sa.Float(precision=10, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('payments', 'amount',
               existing_type=sa.Float(precision=10, asdecimal=3),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('order', 'total_price',
               existing_type=sa.Float(precision=10, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('carts', 'total_price',
               existing_type=sa.Float(precision=10, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('carts', 'price',
               existing_type=sa.Float(precision=10, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
